import type { Session, Decision } from '@/lib/session/types'

const EDGE_CASE_KEYWORDS = ['error', 'fail', 'edge', 'exception', 'timeout', 'retry']
const SCOPE_KEYWORDS = ['scope', 'v1', 'out of scope', 'later', 'separate pr', 'phase']

function categorizeDecision(decision: Decision): 'edge' | 'scope' | 'core' {
  const lower = decision.summary.toLowerCase()
  if (EDGE_CASE_KEYWORDS.some(k => lower.includes(k))) return 'edge'
  if (SCOPE_KEYWORDS.some(k => lower.includes(k))) return 'scope'
  return 'core'
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ')
}

function decisionsTable(decisions: Decision[]): string {
  if (decisions.length === 0) return '_None recorded._\n'
  const header = '| Decision | Rationale | Alternatives Considered |\n|---|---|---|\n'
  const rows = decisions
    .map(d => {
      const alts = d.alternativesConsidered.join('; ') || 'None'
      return `| ${escapeCell(d.summary)} | ${escapeCell(d.rationale)} | ${escapeCell(alts)} |`
    })
    .join('\n')
  return header + rows + '\n'
}

export function generateSpec(session: Session): string {
  const repoLabel = session.repoUrl ?? session.repoLocalPath ?? 'unknown'

  const { core: coreDecisions, edge: edgeDecisions, scope: scopeDecisions } =
    session.decisions.reduce(
      (acc, d) => { acc[categorizeDecision(d)].push(d); return acc },
      { core: [] as Decision[], edge: [] as Decision[], scope: [] as Decision[] }
    )

  // Deduplicate affected files preserving first-seen order
  const affectedFiles = Array.from(
    new Set(session.decisions.flatMap(d => d.relevantFiles))
  )

  const sections: string[] = []

  sections.push('# PR Description\n')

  sections.push('## Summary\n')
  if (coreDecisions.length > 0) {
    sections.push(coreDecisions.map(d => `- ${d.summary}`).join('\n') + '\n')
  } else {
    sections.push('_Not yet captured._\n')
  }

  sections.push('## Problem Statement\n')
  sections.push('_To be filled in after call._\n')

  sections.push('## Technical Approach\n')
  if (coreDecisions.length > 0) {
    sections.push(coreDecisions.map(d => `- ${d.rationale}`).join('\n') + '\n')
  } else {
    sections.push('_Not yet captured._\n')
  }

  sections.push('## Affected Files\n')
  if (affectedFiles.length > 0) {
    sections.push(affectedFiles.map(f => `- \`${f}\``).join('\n') + '\n')
  } else {
    sections.push('_No files recorded._\n')
  }

  sections.push('## New Files\n')
  sections.push('_To be determined._\n')

  sections.push('## Acceptance Criteria\n')
  sections.push('_To be filled in after call._\n')

  sections.push('## Technical Decisions\n')
  sections.push(decisionsTable(coreDecisions))

  sections.push('## Edge Cases\n')
  if (edgeDecisions.length > 0) {
    sections.push(decisionsTable(edgeDecisions))
  } else {
    sections.push('_None flagged._\n')
  }

  sections.push('## Existing Patterns\n')
  if (session.filesRead.length > 0) {
    const unique = Array.from(new Set(session.filesRead.map(f => f.path)))
    sections.push(unique.map(p => `- \`${p}\``).join('\n') + '\n')
  } else {
    sections.push('_No files read during session._\n')
  }

  sections.push('## Scope Boundaries\n')
  if (scopeDecisions.length > 0) {
    sections.push(decisionsTable(scopeDecisions))
  } else {
    sections.push('_None defined._\n')
  }

  sections.push('## Open Questions\n')
  if (session.openQuestions.length > 0) {
    sections.push(
      session.openQuestions.map(q => `- **${q.question}** — ${q.context}`).join('\n') + '\n'
    )
  } else {
    sections.push('_None flagged._\n')
  }

  sections.push(
    `---\n_Generated by Spec Voice from conversation \`${session.id}\` · Repo: ${repoLabel}_\n`
  )

  return sections.join('\n')
}
